twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # Récupération de la clé publique Google Recaptcha dans le fichier .env
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'    

when@test:
    twig:
        strict_variables: true
