<?php

namespace Container90ommTl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WXcrdksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WXcrdks' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WXcrdks'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exoRepo' => ['privates', 'App\\Repository\\ExerciseRepository', 'getExerciseRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'exoRepo' => 'App\\Repository\\ExerciseRepository',
            'manager' => '?',
        ]);
    }
}
