<?php

namespace Container90ommTl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExerciseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cwSPvFs.App\Entity\Exercise' shared service.
     *
     * @return \App\Entity\Exercise
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cwSPvFs": it references class "App\\Entity\\Exercise" but no such service exists.');
    }
}
