<?php

namespace ContainerMtXI8Jb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TAvjUJ8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TAvjUJ8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TAvjUJ8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'difficulty' => ['privates', '.errored..service_locator.TAvjUJ8.App\\Entity\\Difficulty', NULL, 'Cannot autowire service ".service_locator.TAvjUJ8": it references class "App\\Entity\\Difficulty" but no such service exists.'],
            'difficultyRepository' => ['privates', 'App\\Repository\\DifficultyRepository', 'getDifficultyRepositoryService', true],
        ], [
            'difficulty' => 'App\\Entity\\Difficulty',
            'difficultyRepository' => 'App\\Repository\\DifficultyRepository',
        ]);
    }
}
