<?php

namespace Container3FmOvNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CwSPvFsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cwSPvFs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cwSPvFs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exercise' => ['privates', '.errored..service_locator.cwSPvFs.App\\Entity\\Exercise', NULL, 'Cannot autowire service ".service_locator.cwSPvFs": it references class "App\\Entity\\Exercise" but no such service exists.'],
            'exerciseRepository' => ['privates', 'App\\Repository\\ExerciseRepository', 'getExerciseRepositoryService', true],
        ], [
            'exercise' => 'App\\Entity\\Exercise',
            'exerciseRepository' => 'App\\Repository\\ExerciseRepository',
        ]);
    }
}
