<?php

namespace Container3FmOvNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDifficultyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TAvjUJ8.App\Entity\Difficulty' shared service.
     *
     * @return \App\Entity\Difficulty
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TAvjUJ8": it references class "App\\Entity\\Difficulty" but no such service exists.');
    }
}
