<?php

namespace ContainerPi6Kjfu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3.9X6df.App\Entity\Result' shared service.
     *
     * @return \App\Entity\Result
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3.9X6df": it references class "App\\Entity\\Result" but no such service exists.');
    }
}
