<?php

namespace ContainerDJQCsoq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DI3H8yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dI3H_8y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dI3H_8y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'result' => ['privates', '.errored..service_locator.dI3H_8y.App\\Entity\\Result', NULL, 'Cannot autowire service ".service_locator.dI3H_8y": it references class "App\\Entity\\Result" but no such service exists.'],
        ], [
            'result' => 'App\\Entity\\Result',
        ]);
    }
}
