<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDJQCsoq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDJQCsoq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDJQCsoq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDJQCsoq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDJQCsoq\App_KernelDevDebugContainer([
    'container.build_hash' => 'DJQCsoq',
    'container.build_id' => '43c32dd1',
    'container.build_time' => 1649951166,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDJQCsoq');
